---
blank_issues_enabled: false
contact_links:
  - name: Contribution guidelines
    url: https://github.com/devharshthakur/tcs-coding-sheet-py/blob/main/CONTRIBUTING.md
    about: Please read the contribution guidelines before opening an issue.
